# Generated by Django 4.1.5 on 2023-01-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='NOUN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
                ('title', models.CharField(blank=True, default='default', max_length=50)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'MAn'), ('kid', 'Kid')], default='Specific', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('weave_types', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('black', 'Black'), ('specific', 'Specific')], default='Specific', max_length=45)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=60)),
                ('is_publish', models.BooleanField(default=False)),
                ('Witch_brnad', models.ForeignKey(default='brand', on_delete=django.db.models.deletion.DO_NOTHING, to='market.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.type')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_main_image', models.ImageField(blank=True, default='hello', upload_to='media')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shoes')),
            ],
        ),
    ]
