# Generated by Django 4.1.5 on 2023-01-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(default='noun', max_length=45)),
                ('weave_types', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('black', 'Black'), ('specific', 'Specific')], default='Specific', max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=60)),
                ('is_publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(default='noun', max_length=45)),
                ('weave_types', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('black', 'Black'), ('specific', 'Specific')], default='Specific', max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=60)),
                ('is_publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(default='noun', max_length=45)),
                ('weave_types', models.CharField(default='noun', max_length=50)),
                ('ply', models.CharField(choices=[('1', 'Single-ply'), ('2', 'Double-ply')], default='Single-ply', max_length=30)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('black', 'Black'), ('specific', 'Specific')], default='Specific', max_length=45)),
                ('brand', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=60)),
                ('is_publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.category')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(default='noun', max_length=45)),
                ('Shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shirt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.category')),
                ('jeans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.jeans')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shoes')),
            ],
        ),
    ]
