# Generated by Django 4.1.5 on 2023-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='gender',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('kid', 'Kid')], default='Specific', max_length=50),
        ),
    ]
