# Generated by Django 4.1.5 on 2023-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_category_type_alter_jeans_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='Shirt',
        ),
        migrations.RemoveField(
            model_name='set',
            name='category',
        ),
        migrations.RemoveField(
            model_name='set',
            name='jeans',
        ),
        migrations.RemoveField(
            model_name='set',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='set',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='type',
        ),
        migrations.DeleteModel(
            name='Jeans',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
