# Generated by Django 4.1.5 on 2023-01-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_brand_brand_alter_shoes_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='Noun', max_length=50),
        ),
    ]
