# Generated by Django 4.1.5 on 2023-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Product_main_image',
            new_name='product_images',
        ),
        migrations.AddField(
            model_name='shoes',
            name='product_main_images',
            field=models.ImageField(blank=True, default='hello', upload_to='media'),
        ),
    ]
