# Generated by Django 4.1.5 on 2023-01-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_set_shirt_remove_set_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, default='hello', upload_to='images/'),
        ),
    ]
