# Generated by Django 4.1.5 on 2023-01-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_shoes_hotel_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='title',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, default='hello', upload_to='media'),
        ),
    ]
